version: "3.5"

services:
  skeleton-api:
    container_name: skeleton-api
    build: .
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./process.yml:/app/process.yml
    ports:
      - "8080:8080"
    networks:
      - local

networks:
  local:
    name: local
    driver: bridge
